name: Testar STREAB Intel no macOS

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: macos-15-intel

    steps:
      - name: Baixar STREAB Intel direto do servidor
        run: |
          curl -L "https://streab.com/application/streab_mac_intel.zip" -o streab_mac_intel.zip
          ls -lh streab_mac_intel.zip

      - name: Abrir acesso SSH com tmate
        uses: mxschmitt/action-tmate@v3
